global:
    scrape_interval: 15s
    scrape_timeout: 10s

scrape_configs:
  - job_name: "ups"
    static_configs:
      - targets: ['host.docker.internal'] # nut exporter
    metrics_path: /ups_metrics
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_server
      - source_labels: [__param_server]
        target_label: instance
      - target_label: __address__
        replacement: nut-metrics-exporter:9199
