{
 "title": "UPS Monitoring",
 "description": "Monitor your UPS over NUT service. ",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   { "name": "ups", "label": "UPS", "query": { "query": "nut_ups_info" } },
   { "name": "smoothing_interval", "label": "Smoothing", "query": "1m,5m,15m,1h,1d,1w" },
   { "name": "data_source", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Input Voltage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "nut_input_voltage{ups=~\"${ups:pipe}\"}",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  {
   "title": "Output Voltage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "nut_output_voltage{ups=~\"${ups:pipe}\"}",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  {
   "title": "Output Current",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "nut_output_current{ups=~\"${ups:pipe}\"}",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  {
   "title": "Load on UPS",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 10, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nut_ups_load", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Ambient Temperature (degrees C)  [$smoothing_interval]",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "nut_ambient_temperature", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Charge",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "((nut_battery_voltage - 30.5) / (41.1 - 30.5)) * 100",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "nut_battery_voltage{ups=~\"${ups:pipe}\"}",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  {
   "title": "Runtime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "nut_battery_runtime{ups=~\"${ups:pipe}\"}",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  {
   "title": "Status",
   "type": "stat",
   "gridPos": { "h": 2, "w": 16, "x": 4, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "nut_ups_status{flag=~\"ALARM|BOOST|BYPASS|HB|LB|OB|OFF|OL|OVER|RB|TRIM|WAIT\"}",
     "legendFormat": "{{flag}}"
    }
   ]
  },
  {
   "title": "Status Change System Related",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "nut_ups_status{flag=~\"BOOST|BYPASS|FSD|HB|LB|OB|OFF|OL|OVER|RB|SD|ALARM|TRIM\"}",
     "legendFormat": "{{flag}}"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 } },
  {
   "title": "Current value of apparent power (VA) [$smoothing_interval]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "voltamp" } },
   "targets": [
    { "expr": "nut_ups_power", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Current value of real power (W) [$smoothing_interval]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    { "expr": "nut_ups_realpower", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Ambient Temperature (degrees C)  [$smoothing_interval]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "avg_over_time(nut_ambient_temperature{ups=~\"${ups:pipe}\"}[$smoothing_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Load on UPS [$smoothing_interval]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "nut_ups_load", "legendFormat": "{{job}}" }
   ]
  },
  { "title": "Battery", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 } },
  {
   "title": "Charge",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "((nut_battery_voltage - 30.5) / (41.1 - 30.5)) * 100",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  {
   "title": "Runtime",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 10, "x": 2, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "avg_over_time(nut_battery_runtime{ups=~\"${ups:pipe}\"}[$smoothing_interval])",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  {
   "title": "Battery Charge",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "((nut_battery_voltage - 30.5) / (41.1 - 30.5)) * 100",
     "legendFormat": "{{ups}} Current"
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "nut_battery_voltage{ups=~\"${ups:pipe}\"}",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  {
   "title": "Runtime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "nut_battery_runtime{ups=~\"${ups:pipe}\"}",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  {
   "title": "Battery Voltage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 22, "x": 2, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    { "expr": "nut_battery_voltage", "legendFormat": "{{job}}" }
   ]
  },
  {
   "title": "Battery State",
   "type": "state-timeline",
   "gridPos": { "h": 4, "w": 22, "x": 2, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "((nut_battery_voltage - 30.5) / (41.1 - 30.5)) * 100",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "Input", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 52 } },
  {
   "title": "Nominal Input Voltage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 1, "x": 0, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "nut_input_voltage_nominal{}", "legendFormat": "{{ups}}" }
   ]
  },
  {
   "title": "Nominal Input Freq",
   "type": "stat",
   "gridPos": { "h": 3, "w": 1, "x": 1, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "nut_input_frequency_nominal{}", "legendFormat": "{{ups}}" }
   ]
  },
  {
   "title": "Input Voltage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 2, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "avg_over_time(nut_input_voltage[$smoothing_interval])",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  {
   "title": "Input Line Frequency (Hz)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 53 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "expr": "nut_input_frequency{ups=~\"${ups:pipe}\"}",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  {
   "title": "Input Voltage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "nut_input_voltage{ups=~\"${ups:pipe}\"}",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  {
   "title": "Input Frequency",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 59 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "nut_input_frequency{}", "legendFormat": "{{ups}}" }
   ]
  },
  { "title": "Output", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "Nominal Output Voltage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 1, "x": 0, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "nut_output_voltage_nominal{}", "legendFormat": "{{ups}}" }
   ]
  },
  {
   "title": "Nominal Output Freq",
   "type": "stat",
   "gridPos": { "h": 3, "w": 1, "x": 1, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "nut_output_frequency_nominal{}", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Output Voltage",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 2, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "targets": [
    {
     "expr": "avg_over_time(nut_output_voltage{ups=~\"${ups:pipe}\"}[$smoothing_interval])",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  {
   "title": "Output Frequency",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 63 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "targets": [
    {
     "expr": "avg_over_time(nut_output_frequency{ups=~\"${ups:pipe}\"}[$smoothing_interval])",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  {
   "title": "Output Voltage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "nut_output_voltage{ups=~\"${ups:pipe}\"}",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  {
   "title": "Output Frequency",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "rothz" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "nut_output_frequency{}", "legendFormat": "{{ups}}" }
   ]
  },
  {
   "title": "Output Current",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "nut_output_current{ups=~\"${ups:pipe}\"}",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  {
   "title": "Output Current",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 10, "x": 2, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "targets": [
    {
     "expr": "nut_output_current{ups=~\"${ups:pipe}\"}",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  {
   "title": "Nominal Current",
   "type": "stat",
   "gridPos": { "h": 3, "w": 2, "x": 0, "y": 75 },
   "fieldConfig": { "defaults": { "unit": "amp" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "nut_output_current_nominal{ups=~\"${ups:pipe}\"}",
     "legendFormat": "{{ups}}"
    }
   ]
  },
  {
   "title": "PDU outlet",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 },
   "collapsed": true,
   "panels": [
    {
     "title": "Status Change",
     "type": "state-timeline",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 55 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "nut_ups_status{flag=~\"BOOST|BYPASS|FSD|HB|LB|OB|OFF|OL|OVER|RB|SD|ALARM|TRIM\"}",
       "legendFormat": "{{flag}}"
      }
     ]
    }
   ]
  }
 ]
}